### ISSUE TITLE
Device is not changing between iPhone Retina (3.5-inch) and iPhone Retina (4-inch)

### ISSUE THREAD

**Issue by iloris** [toursprung/iOS-Screenshot-Automator#6]
Hi,
I set the devices to all 3 versions of iOS devices like this
```set allDevices to {"iPhone Retina (3.5-inch)" , "iPhone Retina (4-inch)", "iPad Retina"}```

And it correctly loop 3 times but it doesn't change from iPhone Retina (3.5-inch) to iPhone Retina (4-inch), and the log says it correctly change the device. It correctly switch to iPad.

The menu to select the devices is like this:
![screenshot 2014-01-23 16 12 11](https://f.cloud.github.com/assets/1638989/1990827/74eb0c7a-848c-11e3-90c2-01dc4051b851.png)

Is it something that other people experiences?

**Comment by KrauseFx** [comment]
This is now actually https://fastlane.tools/snapshot
