### ISSUE TITLE
Does not work in Xcode 9

### ISSUE THREAD

**Issue by alfrednerstu** [toursprung/iOS-Screenshot-Automator#8]
The SpringBoard.app isn't in the CoreServices folder any more. Any idea how to do this in Xcode 9? Thanks!

**Comment by KrauseFx** [comment]
Yeah, [fastlane](https://fastlane.tools) supports the latest Xcode, use [snapshot](https://docs.fastlane.tools/actions/snapshot) to automate your screenshots 👍
